- name: Configure Wordpress
  hosts: wordpress-server
  remote_user: root
  # remote_user: user
  # sudo: yes

  tasks:
  - name: Clean up previous run with a hammer
    shell: rm -rf /opt/assets
  - name: Make the dirs
    file:
      path: /opt/assets
      state: directory
  #- name: Make the dirs 2
  #  file:
  #    path: /opt/assets/wordpress
  #    state: directory
  - name: Clone the repo
    git:
      repo: https://github.com/alilynton/ansible-examples.git
      version: master
      dest: /opt/assets
      accept_hostkey: yes
  - name: extract the .tar.gz
    unarchive: 
      src: /opt/assets/populate-wordpress/wordpress.tar.gz
      dest: /opt/assets/wordpress
      remote_src: yes
  - name: place the files
    copy: 
      src: /opt/assets/wordpress/wordpress/wp-content/
      dest: /srv/wordpress/wp-content/
      remote_src: yes

  - name: load the sql
    shell: mysql < /opt/assets/wordpress/wordpress/wordpress.sql
